name: Generate VCF File

on:
  workflow_dispatch:   # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Run Script
        run: python vcf_bot.py
      - name: Upload VCF
        uses: actions/upload-artifact@v3
        with:
          name: contacts
          path: contacts.vcf
